import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getValidatedUserId } from "@/lib/auth/get-user";

const saveExportSchema = z.object({
  projectId: z.string().uuid("Invalid project ID"),
  exportedFileUrl: z.string().url("Invalid file URL"),
});

const generateExportSchema = z.object({
  projectId: z.string().uuid("Invalid project ID"),
});

function generateReportHtml(
  report: {
    title: string;
    projectName: string;
    projectLocation: string | null;
    generatedAt: string;
    totalImages: number;
    sections: Array<{
      category: string;
      summary: string;
      recommendations: string;
      images: Array<{
        imageUrl: string;
        caption: string;
        finding: string;
        recommendation: string;
      }>;
    }>;
  },
  author: { name: string; companyName: string | null } | null
): string {
  const authorName = author?.name || "";
  const companyName = author?.companyName || "";
  const authorLine = companyName ? `${authorName} - ${companyName}` : authorName;

  const categoryLabels: Record<string, string> = {
    crop_health: "Crop Health",
    erosion: "Erosion",
    damage: "Damage",
    irrigation: "Irrigation",
    general: "General",
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
  };

  const sectionsHtml = report.sections
    .map(
      (section) => `
      <div style="margin-bottom: 32px; page-break-inside: avoid;">
        <h2 style="color: #315f9b; border-bottom: 2px solid #315f9b; padding-bottom: 8px; margin-bottom: 16px;">
          ${categoryLabels[section.category] || section.category}
        </h2>
        <div style="background: #f5f5f5; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
          <h3 style="color: #666; font-size: 14px; margin: 0 0 8px 0;">Summary</h3>
          <p style="margin: 0; line-height: 1.6;">${section.summary}</p>
        </div>
        <div style="background: #e8f5e9; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
          <h3 style="color: #2e7d32; font-size: 14px; margin: 0 0 8px 0;">Recommendations</h3>
          <p style="margin: 0; line-height: 1.6;">${section.recommendations}</p>
        </div>
        <div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 16px;">
          ${section.images
            .map(
              (img) => `
            <div style="background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
              <img src="${img.imageUrl}" alt="${img.caption}" style="width: 100%; height: 150px; object-fit: cover;" />
              <div style="padding: 12px;">
                <p style="font-size: 12px; color: #666; margin: 0 0 8px 0;"><strong>Caption:</strong> ${img.caption}</p>
                <p style="font-size: 12px; color: #444; margin: 0 0 8px 0;"><strong>Finding:</strong> ${img.finding}</p>
                <p style="font-size: 12px; color: #2e7d32; margin: 0;"><strong>Recommendation:</strong> ${img.recommendation}</p>
              </div>
            </div>
          `
            )
            .join("")}
        </div>
      </div>
    `
    )
    .join("");

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
        .header { border-bottom: 3px solid #315f9b; padding-bottom: 20px; margin-bottom: 30px; }
        .header h1 { color: #315f9b; margin: 0 0 10px 0; }
        .meta { color: #666; font-size: 14px; }
        .author { color: #666; font-size: 14px; margin-top: 10px; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #999; text-align: center; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${report.title}</h1>
        <div class="meta">
          <p style="margin: 5px 0;"><strong>Project:</strong> ${report.projectName}${report.projectLocation ? ` - ${report.projectLocation}` : ""}</p>
          <p style="margin: 5px 0;"><strong>Generated:</strong> ${formatDate(report.generatedAt)}</p>
          <p style="margin: 5px 0;"><strong>Total Images:</strong> ${report.totalImages}</p>
        </div>
        ${authorLine ? `<p class="author"><strong>Prepared by:</strong> ${authorLine}</p>` : ""}
      </div>
      ${sectionsHtml}
      <div class="footer">
        <p>Generated by FieldSpec - Market Intelligence Platform</p>
      </div>
    </body>
    </html>
  `;
}

export async function POST(request: NextRequest) {
  try {
    const userId = await getValidatedUserId(request);
    if (!userId) {
      return NextResponse.json(
        { error: { message: "Unauthorized", code: "UNAUTHORIZED" } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const result = generateExportSchema.safeParse(body);

    if (!result.success) {
      return NextResponse.json(
        { error: { message: result.error.issues[0].message, code: "VALIDATION_ERROR" } },
        { status: 400 }
      );
    }

    const { projectId } = result.data;

    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { name: true, companyName: true },
    });

    const report = await prisma.report.findUnique({
      where: { projectId },
      include: { project: true },
    });

    if (!report || report.project.userId !== userId) {
      return NextResponse.json(
        { error: { message: "Report not found", code: "NOT_FOUND" } },
        { status: 404 }
      );
    }

    const html = generateReportHtml(report.content as any, user);
    return new NextResponse(html, {
      status: 200,
      headers: { "Content-Type": "text/html" },
    });
  } catch (error) {
    console.error("POST /api/report/export error:", error);
    return NextResponse.json(
      { error: { message: "Internal server error", code: "INTERNAL_ERROR" } },
      { status: 500 }
    );
  }
}

export async function PUT(request: NextRequest) {
  try {
    const userId = await getValidatedUserId(request);
    if (!userId) {
      return NextResponse.json(
        { error: { message: "Unauthorized", code: "UNAUTHORIZED" } },
        { status: 401 }
      );
    }

    const body = await request.json();
    const result = saveExportSchema.safeParse(body);

    if (!result.success) {
      return NextResponse.json(
        { error: { message: result.error.issues[0].message, code: "VALIDATION_ERROR" } },
        { status: 400 }
      );
    }

    const { projectId, exportedFileUrl } = result.data;

    const project = await prisma.project.findFirst({
      where: { id: projectId, userId },
    });

    if (!project) {
      return NextResponse.json(
        { error: { message: "Project not found", code: "NOT_FOUND" } },
        { status: 404 }
      );
    }

    const existingReport = await prisma.report.findUnique({
      where: { projectId },
    });

    if (!existingReport) {
      return NextResponse.json(
        { error: { message: "Report not found", code: "NOT_FOUND" } },
        { status: 404 }
      );
    }

    const updatedReport = await prisma.report.update({
      where: { id: existingReport.id },
      data: {
        exportedFileUrl,
        status: "exported",
      },
    });

    return NextResponse.json(
      {
        data: {
          id: updatedReport.id,
          title: updatedReport.title,
          status: updatedReport.status,
          exportedFileUrl: updatedReport.exportedFileUrl,
          updatedAt: updatedReport.updatedAt,
        },
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("PUT /api/report/export error:", error);
    return NextResponse.json(
      { error: { message: "Internal server error", code: "INTERNAL_ERROR" } },
      { status: 500 }
    );
  }
}
