export const tokens = {
  colors: {
    primary: "var(--sys-primary)",
    onPrimary: "var(--sys-on-primary)",
    primaryContainer: "var(--sys-primary-container)",
    onPrimaryContainer: "var(--sys-on-primary-container)",
    secondary: "var(--sys-secondary)",
    onSecondary: "var(--sys-on-secondary)",
    secondaryContainer: "var(--sys-secondary-container)",
    onSecondaryContainer: "var(--sys-on-secondary-container)",
    tertiary: "var(--sys-tertiary)",
    onTertiary: "var(--sys-on-tertiary)",
    tertiaryContainer: "var(--sys-tertiary-container)",
    onTertiaryContainer: "var(--sys-on-tertiary-container)",
    error: "var(--sys-error)",
    onError: "var(--sys-on-error)",
    errorContainer: "var(--sys-error-container)",
    onErrorContainer: "var(--sys-on-error-container)",
    background: "var(--sys-surface-roles-surface)",
    onBackground: "var(--sys-surface-roles-on-surface)",
    surface: "var(--sys-surface-roles-surface)",
    onSurface: "var(--sys-surface-roles-on-surface)",
    surfaceContainerLow: "var(--sys-surface-roles-surface-container-low)",
    surfaceContainer: "var(--sys-surface-roles-surface-container)",
    surfaceContainerHigh: "var(--sys-surface-roles-surface-container-high)",
    surfaceVariant: "var(--sys-surface-roles-surface-variant)",
    onSurfaceVariant: "var(--sys-surface-roles-on-surface-variant)",
    outline: "var(--sys-outline-roles-outline)",
    outlineVariant: "var(--sys-outline-roles-outline-variant)",
  },
  colorsLight: {
    primary: "#315f9b",
    onPrimary: "#ffffff",
    primaryContainer: "#d8e4f3",
    onPrimaryContainer: "#0c1827",
    secondary: "#369596",
    onSecondary: "#ffffff",
    secondaryContainer: "#d9f1f2",
    onSecondaryContainer: "#0d2526",
    tertiary: "#8e603d",
    onTertiary: "#ffffff",
    tertiaryContainer: "#f0e4db",
    onTertiaryContainer: "#24180f",
    error: "#c93636",
    onError: "#ffffff",
    errorContainer: "#f4d7d7",
    onErrorContainer: "#280b0b",
    background: "#fcfcfc",
    onBackground: "#191919",
    surface: "#fcfcfc",
    onSurface: "#191919",
    surfaceContainerLow: "#fafaf9",
    surfaceContainer: "#f5f5f5",
    surfaceContainerHigh: "#ebebeb",
    surfaceVariant: "#e3e5e8",
    onSurfaceVariant: "#5d636f",
    outline: "#747c8b",
    outlineVariant: "#c7cad1",
  },
  colorsDark: {
    primary: "#b1c8e6",
    onPrimary: "#182f4e",
    primaryContainer: "#254774",
    onPrimaryContainer: "#d8e4f3",
    secondary: "#8ed6d7",
    onSecondary: "#1b4a4b",
    secondaryContainer: "#287071",
    onSecondaryContainer: "#d9f1f2",
    tertiary: "#d1ae94",
    onTertiary: "#47301f",
    tertiaryContainer: "#6b482e",
    onTertiaryContainer: "#f0e4db",
    error: "#eaaeae",
    onError: "#511515",
    errorContainer: "#792020",
    onErrorContainer: "#f4d7d7",
    background: "#0f0f0f",
    onBackground: "#e6e6e6",
    surface: "#0f0f0f",
    onSurface: "#e6e6e6",
    surfaceContainerLow: "#1a1a1a",
    surfaceContainer: "#242424",
    surfaceContainerHigh: "#2e2e2e",
    surfaceVariant: "#464a53",
    onSurfaceVariant: "#9096a2",
    outline: "#9096a2",
    outlineVariant: "#464a53",
  },
  spacing: {
    xs: "var(--sys-spacing-spacing-xs)",
    sm: "var(--sys-spacing-spacing-sm)",
    md: "var(--sys-spacing-spacing-md)",
    lg: "var(--sys-spacing-spacing-lg)",
    xl: "var(--sys-spacing-spacing-xl)",
    xxl: "var(--sys-spacing-spacing-xxl)",
  },
  elevation: {
    level1: "var(--sys-elevation-3d-pnumbra)",
    level2: "var(--sys-elevation-6dp-penumbra)",
    level3: "var(--sys-elevation-8dp)",
    level4: "var(--sys-elevation-12dp-penumbra)",
  },
  radius: {
    xs: "var(--sys-radius-xs)",
    sm: "var(--sys-radius-sm)",
    md: "var(--sys-radius-md)",
    lg: "var(--sys-radius-lg)",
    xl: "var(--sys-radius-xl)",
    pill: "var(--sys-radius-pill)",
  },
  typography: {
    displayLarge: {
      fontFamily: "var(--sys-typescale-display-large-fontfamily)",
      fontSize: "var(--sys-typescale-display-large-fontsize)",
      fontWeight: "var(--sys-typescale-display-large-fontweight)",
      lineHeight: "var(--sys-typescale-display-large-lineheight)",
      letterSpacing: "var(--sys-typescale-display-large-letterspacing)",
    },
    displayMedium: {
      fontFamily: "var(--sys-typescale-display-medium-fontfamily)",
      fontSize: "var(--sys-typescale-display-medium-fontsize)",
      fontWeight: "var(--sys-typescale-display-medium-fontweight)",
      lineHeight: "var(--sys-typescale-display-medium-lineheight)",
      letterSpacing: "var(--sys-typescale-display-medium-letterspacing)",
    },
    displaySmall: {
      fontFamily: "var(--sys-typescale-display-small-fontfamily)",
      fontSize: "var(--sys-typescale-display-small-fontsize)",
      fontWeight: "var(--sys-typescale-display-small-fontweight)",
      lineHeight: "var(--sys-typescale-display-small-lineheight)",
      letterSpacing: "var(--sys-typescale-display-small-letterspacing)",
    },
    headlineLarge: {
      fontFamily: "var(--sys-typescale-headline-large-fontfamily)",
      fontSize: "var(--sys-typescale-headline-large-fontsize)",
      fontWeight: "var(--sys-typescale-headline-large-fontweight)",
      lineHeight: "var(--sys-typescale-headline-large-lineheight)",
      letterSpacing: "var(--sys-typescale-headline-large-letterspacing)",
    },
    headlineMedium: {
      fontFamily: "var(--sys-typescale-headline-medium-fontfamily)",
      fontSize: "var(--sys-typescale-headline-medium-fontsize)",
      fontWeight: "var(--sys-typescale-headline-medium-fontweight)",
      lineHeight: "var(--sys-typescale-headline-medium-lineheight)",
      letterSpacing: "var(--sys-typescale-headline-medium-letterspacing)",
    },
    headlineSmall: {
      fontFamily: "var(--sys-typescale-headline-small-fontfamily)",
      fontSize: "var(--sys-typescale-headline-small-fontsize)",
      fontWeight: "var(--sys-typescale-headline-small-fontweight)",
      lineHeight: "var(--sys-typescale-headline-small-lineheight)",
      letterSpacing: "var(--sys-typescale-headline-small-letterspacing)",
    },
    titleLarge: {
      fontFamily: "var(--sys-typescale-title-large-fontfamily)",
      fontSize: "var(--sys-typescale-title-large-fontsize)",
      fontWeight: "var(--sys-typescale-title-large-fontweight)",
      lineHeight: "var(--sys-typescale-title-large-lineheight)",
      letterSpacing: "var(--sys-typescale-title-large-letterspacing)",
    },
    titleMedium: {
      fontFamily: "var(--sys-typescale-title-medium-fontfamily)",
      fontSize: "var(--sys-typescale-title-medium-fontsize)",
      fontWeight: "var(--sys-typescale-title-medium-fontweight)",
      lineHeight: "var(--sys-typescale-title-medium-lineheight)",
      letterSpacing: "var(--sys-typescale-title-medium-letterspacing)",
    },
    titleSmall: {
      fontFamily: "var(--sys-typescale-title-small-fontfamily)",
      fontSize: "var(--sys-typescale-title-small-fontsize)",
      fontWeight: "var(--sys-typescale-title-small-fontweight)",
      lineHeight: "var(--sys-typescale-title-small-lineheight)",
      letterSpacing: "var(--sys-typescale-title-small-letterspacing)",
    },
    bodyLarge: {
      fontFamily: "var(--sys-typescale-body-large-fontfamily)",
      fontSize: "var(--sys-typescale-body-large-fontsize)",
      fontWeight: "var(--sys-typescale-body-large-fontweight)",
      lineHeight: "var(--sys-typescale-body-large-lineheight)",
      letterSpacing: "var(--sys-typescale-body-large-letterspacing)",
    },
    bodyMedium: {
      fontFamily: "var(--sys-typescale-body-medium-fontfamily)",
      fontSize: "var(--sys-typescale-body-medium-fontsize)",
      fontWeight: "var(--sys-typescale-body-medium-fontweight)",
      lineHeight: "var(--sys-typescale-body-medium-lineheight)",
      letterSpacing: "var(--sys-typescale-body-medium-letterspacing)",
    },
    bodySmall: {
      fontFamily: "var(--sys-typescale-body-small-fontfamily)",
      fontSize: "var(--sys-typescale-body-small-fontsize)",
      fontWeight: "var(--sys-typescale-body-small-fontweight)",
      lineHeight: "var(--sys-typescale-body-small-lineheight)",
      letterSpacing: "var(--sys-typescale-body-small-letterspacing)",
    },
    labelLarge: {
      fontFamily: "var(--sys-typescale-label-large-fontfamily)",
      fontSize: "var(--sys-typescale-label-large-fontsize)",
      fontWeight: "var(--sys-typescale-label-large-fontweight)",
      lineHeight: "var(--sys-typescale-label-large-lineheight)",
      letterSpacing: "var(--sys-typescale-label-large-letterspacing)",
    },
    labelMedium: {
      fontFamily: "var(--sys-typescale-label-medium-fontfamily)",
      fontSize: "var(--sys-typescale-label-medium-fontsize)",
      fontWeight: "var(--sys-typescale-label-medium-fontweight)",
      lineHeight: "var(--sys-typescale-label-medium-lineheight)",
      letterSpacing: "var(--sys-typescale-label-medium-letterspacing)",
    },
    labelSmall: {
      fontFamily: "var(--sys-typescale-label-small-fontfamily)",
      fontSize: "var(--sys-typescale-label-small-fontsize)",
      fontWeight: "var(--sys-typescale-label-small-fontweight)",
      lineHeight: "var(--sys-typescale-label-small-lineheight)",
      letterSpacing: "var(--sys-typescale-label-small-letterspacing)",
    },
  },
};

export type ThemeMode = "light" | "dark";

export function getThemeColors(mode: ThemeMode) {
  return mode === "light" ? tokens.colorsLight : tokens.colorsDark;
}

export type Tokens = typeof tokens;
